version: '3.4'

services:
  frontend:
    build: frontend
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 80:80

  backend:
    build: backend
    depends_on:
      - db
    links:
      - db
    ports:
    - 8080:80

  db:
    image: percona:5.7
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
      - '--sql-mode=IGNORE_SPACE,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    environment:
      MYSQL_ROOT_PASSWORD: greedisgood
      MYSQL_DATABASE: site
      MYSQL_USER: site
      MYSQL_PASSWORD: ims0str0ng
    volumes:
      - mysql-data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
    links:
      - db

volumes:
  mysql-data:
